; File:			ex1_14.scm
; Date created: 2017-08-15 
; Ref:			https://mitpress.mit.edu/sicp/full-text/book/book-Z-H-11.html#%_sec_1.2.2
; Description:	Draw the tree illustrating the process generated by the count-change 
;				procedure of section 1.2.2 in making change for 11 cents. What are the 
;				orders of growth of the space and number of steps used by this process as 
;				the amount to be changed increases?
	
(define (first-denomination kinds-of-coins)
	(cond 
		((= kinds-of-coins 1) 1)
		((= kinds-of-coins 2) 5)
		((= kinds-of-coins 3) 10)
		((= kinds-of-coins 4) 25)
		((= kinds-of-coins 5) 50)
	)
)

(define (cc amount kinds-of-coins)
	(cond 
		((= amount 0) 1)
		((or (< amount 0) (= kinds-of-coins 0)) 0)
		(else (+ 
			(cc amount (- kinds-of-coins 1)) 
			(cc (- amount (first-denomination kinds-of-coins)) kinds-of-coins)))
	)
)

; entry point 
(define (count-change amount)
	(cc amount 5)
)

; additional space is O(n)
; additional number of steps is O(n^5)

; truncated tree illustration
;
;                                           cc(11,5)
;                                              / \
;                                       cc(11,4) cc(-39,5)
;                                        /   \       0
;                                  cc(11,3) cc(-14,4)
;                                    /   \      0
;                            cc(11,2)     cc(1,3)
;                           / \             /   \
;                   cc(11,1) cc(6,2)     cc(1,2) cc(-7,3)  
;                  /\         /\           /   \     0
;           cc(11,0) cc(10,1).. c(1,2) cc(1,0) cc(0,1)
;              0      /\      1    /\         0       1
;                 ...   ...   c(0,2) c(1,1)
;                  0    cc(0,1) 0      /\
;                          1     c(1,0) c(0,1)
;                                   0      1

; sum the ones in the tree to get 4, which is indeed the answer returned by (count-change 11)